config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  get 'pages/about', to: 'pages#about'

  resources :articles do
  	member do
  		put :like, to: 'articles#upvote'
  		put :unlike, to: 'articles#downvote'
  	end
  end

  resources :articles do
    resources :comments
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user

	#don't touch this comments
	has_many :comments
	
  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  acts_as_votable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  #delete this if it doesn't work
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy

	#delete this if it doesn't work
	has_many :comments
	
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: {case_sensitive: false}, 
	length: {minimum: 3, maximum: 25}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 105},
	uniqueness: {case_sensitive: false},
	format: { with: VALID_EMAIL_REGEX }

	has_secure_password
	acts_as_voter

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must logged in to perfom that action"
			redirect_to root_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy, :upvote, :downvote]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    @article.user = current_user

    if @article.save
    	flash[:notice] = "Article was successfully created"
    	redirect_to article_path(@article)
    else
    	render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  def upvote
    @article = Article.find(params[:id])
    @article.upvote_by(current_user)
    redirect_to root_path
  end

  def downvote
    @article = Article.find(params[:id])
    @article.downvote_by(current_user)
    redirect_to root_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
    	params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "I see what you did there. You can only edit or delete your own articles"
        redirect_to articles_path
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Incorrect Email/Password"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You've been logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      session[:user_id] = @user.id
  		flash[:success] = "Welcome to the 2iDIOTS #{@user.username}"
  		redirect_to articles_path
  	else
  		render 'new'
  	end
  end

  def edit
  	
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "Your account was updated successfully"
  		redirect_to articles_path
  	else
  		render 'edit'
  	end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "Don't do that please. That's not your account"
      redirect_to articles_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Why do you want to do that? Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<table>
  <tr>
  	<th>Title</th>
  	<th>Description</th>
  </tr>

  <% obj.each do |article| %>
  <tr>
  	<td><%= article.title %></td>
  	<td><%= article.description %></td>
    <td>Created By: <%= article.user.username if article.user %>, 
      <%= time_ago_in_words(article.created_at) %> ago, 
      last updated: <%= time_ago_in_words(article.updated_at) %> ago</td>
    <% if logged_in? %>
      <td><%= link_to "Upvote", like_article_path(article), method: :put, local: true %></td>
      <td><%= link_to "Downvote", unlike_article_path(article), method: :put, local: true %></td>
      <td><%= article.weighted_score %></td>
    <% end %>
    <td><%= link_to 'Show', article_path(article) %></td>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
    	<td><%= link_to 'Edit', edit_article_path(article) %></td>
    	<td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2><% pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
	<ul>
	<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @article do |f| %>
<p><%= f.label :title %><br />
	<%= f.text_field :title %></p>
<p><%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
<p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<% if logged_in? %>
<p><%= link_to "Create new article", new_article_path %></p>
<% end %>
<%= will_paginate %>
<%= render 'article', obj: @articles %>
<%= will_paginate %>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>
<% if @article.user %>
<ul>
	<li>Created by:</li>
	<li><%= link_to @article.user.username, user_path(@article.user) %></li>
	<li><small><% pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
</ul>
<% end %>
<p>Description: <%= @article.description %></p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
	<p><%= comment.user.username if comment.user %></p>
	<p><%= time_ago_in_words(comment.created_at) %> ago</p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  	<%= link_to 'Destroy Comment', [comment.article, comment],
               	method: :delete,
               	data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>
<%= render 'comments/form' %>

<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
	<%= link_to "Edit this article", edit_article_path(@article) %> |
	<%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"} %> |
<% end %>
<%= link_to "Back to articles", articles_path %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label 'Write a comment' %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-container">

  <div class="nav-title">
    <h1><%= link_to '2iDIOTS', root_path %></h1>
  </div>

  <div class="nav-menu">
    <ul>
      <li><input type="text" placeholder ="Search"></li>
      <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li>Insert dropdown list here for:</li>
        <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
        <li><%= link_to 'View Profile', user_path(current_user) %></li>
        <% if current_user.admin? %>
          <li><%= link_to 'View all Users', users_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign up', signup_path %></li>
      <% end %>
    </ul>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<%= link_to 'Posts', articles_path %>

app/views/posts/new.html.erb
<H1>Create Post</H1>


<%= form_with scope: :posts, url: posts_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2><% pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>
	<ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @user do |f| %>
<p><%= f.label :username %><br />
	<%= f.text_field :username, placeholder: "Enter Username" %>
</p>
<p><%= f.label :email %><br />
	<%= f.email_field :email, placeholder: "Enter Email" %>
</p>
<p><%= f.label :password %><br />
	<%= f.password_field :password, placeholder: "Enter Password" %>
</p>
<p><%= f.submit(@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= will_paginate %>
<% @users.each do |user| %>
	<ul>
		<li><%= link_to user.username, user_path(user) %></li>
		<li><small><% pluralize(user.articles.count, "article") if user.articles %></small></li>
		<% if logged_in? && current_user.admin? %>
			<li><%= link_to "Delete this user", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user and all the their articles?"} %></li>
		<% end %>
	</ul>
<% end %>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>
<h4><%= @user.username %>'s articles</h4>
<%= will_paginate @user_articles %>
<%= render 'articles/article', obj: @user_articles %>
<%= will_paginate @user_articles %>

app/views/welcome/index.html.erb
<h1>HELLO WORLD</h1>